# This file is automatically loaded by docker-compose and overrides
# the main docker-compose.yml for local development

services:
  nginx:
    volumes:
      # Override with local nginx config for development
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

  main-app:
    build:
      context: ../aides-simplifiees-app
      dockerfile: Dockerfile
    image: aides-simplifiees-app:dev  # Override with local build tag
    environment:
      # NODE_ENV: development
      LOG_LEVEL: debug
      SESSION_DRIVER: memory
    volumes:
      - ../aides-simplifiees-app:/app
      - /app/node_modules  # Preserve node_modules in container
      - /app/build        # Preserve build directory
    ports:
      - "3333:3333" # Expose main app port directly for local access
      - "9229:9229"  # Node.js debugging port

  openfisca:
    build:
      context: ../aides-calculatrice-back
      dockerfile: Dockerfile
    image: aides-calculatrice-back:dev  # Override with local build tag
    volumes:
      - ../aides-calculatrice-back/aides_calculatrice_back:/app/aides_calculatrice_back
      - ../aides-calculatrice-back/pyproject.toml:/app/pyproject.toml
      - /app/__pycache__  # Preserve Python cache in container
    ports:
      - "5001:5000"  # Expose OpenFisca calculation service directly (5001 to avoid macOS AirPlay conflict)
      - "5678:5678"  # Python debugging port (debugpy)

  db:
    ports:
      # Expose Postgres port directly for local access
      - "5432:5432"

  db-migrate:
    build:
      context: ../aides-simplifiees-app
      dockerfile: Dockerfile
    image: aides-simplifiees-app:dev  # Override with local build tag
    environment:
      NODE_ENV: development
